### ISSUE TITLE
Failed to marshal state 

### ISSUE THREAD

**Issue by sojjan1337** [magodo/tfmerge#1]
Hi!

I have a directory with plenty of .tfstate files. I want to merge them into one. 1.tfstate to 200.tfstate
But i get 200 errors saying:

I ran "tfmerge -o 1.tfstate *"

```
showing state file /tfstate/done/100.tfstate: exit status 1
Failed to marshal state to json: no schema found for data.aws_sns_topic.sns_topic (in provider registry.terraform.io/-/aws)git/scripts/done/100.tfstate: exit status 1
Failed to marshal state to json: no schema found for data.aws_sns_topic.sns_topic (in provider registry.terraform.io/-/aws)
```

Also when i tried this:
 "tfmerge -o 7.tfstate 8.tfstate 9.tfstate" i got:

 
```
1 error occurred:
	* showing state file /tfstate/done/9.tfstate: exit status 1
Failed to marshal state to json: schema version 2 for aws_security_group_rule.instances_egress_all in state does not match version 0 from the provider
```

Thanks for helping out!

**Comment by sojjan1337** [comment]
driftctl scan --from tfstate://test/**/*.tfstate did the trick

**Comment by magodo** [comment]
@sojjan1337 `tfmerge` uses `terraform` under the hood for kinds of terraform commands, especially the `terraform state show`/`terraform show` command for the errors you have run into. This command requires you have a initialized terraform workspace (i.e. has `terraform init` being run). `tfmerge` by default use the `cwd` as the workspace, but you can switch it to something else via `--chdir`. The problem here is due to the provider in the workspace is of old version, which can not be used to show state files derived from a newer provider version.
